description: "Восстановление пароля"
/request:
	post:
		description: "Запрос на восстановление пароля"
		is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post.raml
		body:
			application/json:
				example: !include example/request.json
/check-code:
	post:
		description: "Проверка кода активации"
		is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/put.raml
		body:
			application/json:
				example: !include example/check-code.json
/confirm:
	post:
		description: "Назначение нового пароля"
		is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/put.raml
		body:
			application/json:
				example: !include example/confirm.json
