description: "Восстановление пароля"
/request:
    post:
        description: "Запрос на востановление пароля"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/create.raml
        body:
            application/json:
                example: !include example/restore.json
        responses:
            202:
                description: |
                    []
/check-code:
    post:
        description: "Проверка смс-кода и назначение нового пароля"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/create.raml
        body:
            application/json:
                example: !include example/restore-with-code.json
/confirm:
    post:

        description: "Запрос смс при помощи хеш кода из письма"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/create.raml
        body:
            application/json:
                example: !include example/confirm.json
/resend-code:
    post:
        description: "Повторная отправка кода на email"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/create.raml
        body:
            application/json:
                example: !include example/resend-code.json